// Generated by scripts/generate_foundation_audio.py.
import type { ChordId } from './curriculum';
export const FOUNDATION_AUDIO_MODULES: Record<ChordId, number> = {
  'C-E-G': require('../../assets/audio/foundation-v1/red-C4-E4-G4.mp3'),
  'C-F-A': require('../../assets/audio/foundation-v1/C4-F4-A4.mp3'),
  'B-D-G': require('../../assets/audio/foundation-v1/B3-D4-G4.mp3'),
  'A-C-F': require('../../assets/audio/foundation-v1/A3-C4-F4.mp3'),
  'D-G-B': require('../../assets/audio/foundation-v1/D4-G4-B4.mp3'),
  'E-G-C': require('../../assets/audio/foundation-v1/E4-G4-C5.mp3'),
  'F-A-C': require('../../assets/audio/foundation-v1/F4-A4-C5.mp3'),
  'G-B-D': require('../../assets/audio/foundation-v1/G4-B4-D5.mp3'),
  'G-C-E': require('../../assets/audio/foundation-v1/G4-C5-E5.mp3'),
  'A-C#-E': require('../../assets/audio/foundation-v1/A3-Csharp4-E4.mp3'),
  'D-F#-A': require('../../assets/audio/foundation-v1/D4-Fsharp4-A4.mp3'),
  'E-G#-B': require('../../assets/audio/foundation-v1/E4-Gsharp4-B4.mp3'),
  'Bb-D-F': require('../../assets/audio/foundation-v1/Bb3-D4-F4.mp3'),
  'Eb-G-Bb': require('../../assets/audio/foundation-v1/Eb4-G4-Bb4.mp3'),
};
