#!/usr/bin/env python3
"""Render all fourteen fixed-register Eguchi chords. No timing, pitch, register, or velocity randomization."""
import argparse
import hashlib
import json
import random
import tempfile
from pathlib import Path

from generate_audio_pack import RenderConfig, build_midi, render_audio, run_ffmpeg

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "frontend/assets/audio/foundation-v1"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--soundfont", required=True)
    args = parser.parse_args()
    OUTPUT.mkdir(parents=True, exist_ok=True)
    config = RenderConfig(1, [4], 120, 3000, 0, 0, 80, 0, 44100, "mp3")
    definitions = [
        ("C-E-G", ["C4", "E4", "G4"], [60, 64, 67]),
        ("C-F-A", ["C4", "F4", "A4"], [60, 65, 69]),
        ("B-D-G", ["B3", "D4", "G4"], [59, 62, 67]),
        ("A-C-F", ["A3", "C4", "F4"], [57, 60, 65]),
        ("D-G-B", ["D4", "G4", "B4"], [62, 67, 71]),
        ("E-G-C", ["E4", "G4", "C5"], [64, 67, 72]),
        ("F-A-C", ["F4", "A4", "C5"], [65, 69, 72]),
        ("G-B-D", ["G4", "B4", "D5"], [67, 71, 74]),
        ("G-C-E", ["G4", "C5", "E5"], [67, 72, 76]),
        ("A-C#-E", ["A3", "C#4", "E4"], [57, 61, 64]),
        ("D-F#-A", ["D4", "F#4", "A4"], [62, 66, 69]),
        ("E-G#-B", ["E4", "G#4", "B4"], [64, 68, 71]),
        ("Bb-D-F", ["Bb3", "D4", "F4"], [58, 62, 65]),
        ("Eb-G-Bb", ["Eb4", "G4", "Bb4"], [63, 67, 70]),
    ]
    entries = {}
    imports = []
    for chord, names, notes in definitions:
        stem = "red-C4-E4-G4" if chord == "C-E-G" else "-".join(names).replace("#", "sharp")
        midi = OUTPUT / (stem + ".mid")
        audio = OUTPUT / (stem + ".mp3")
        build_midi(midi, notes, random.Random(0), config)
        with tempfile.TemporaryDirectory() as temporary:
            wav = Path(temporary) / "chord.wav"
            render_audio(args.soundfont, midi, wav, config.sample_rate)
            run_ffmpeg(wav, audio, ["-t", "4.5", "-codec:a", "libmp3lame", "-b:a", "192k"], None)
        entries[chord] = {
            "chord": chord,
            "notes": names,
            "midiNotes": notes,
            "noteOnMs": [0, 0, 0],
            "heldMs": 3000,
            "velocity": [80, 80, 80],
            "audioFile": audio.name,
            "midiFile": midi.name,
            "sha256": hashlib.sha256(audio.read_bytes()).hexdigest(),
        }
        imports.append(f"  '{chord}': require('../../assets/audio/foundation-v1/{audio.name}'),")
    manifest = {
        "protocol": "eguchi-foundation-1",
        "concertAHz": 440,
        "instrument": "General MIDI acoustic grand piano",
        "soundfont": Path(args.soundfont).name,
        "adaptation": "Synthesized piano; not official Ichionkai recordings.",
        "entries": entries,
    }
    (OUTPUT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    source = (
        "// Generated by scripts/generate_foundation_audio.py.\nimport type { ChordId } from './curriculum';\nexport const FOUNDATION_AUDIO_MODULES: Record<ChordId, number> = {\n"
        + "\n".join(imports)
        + "\n};\n"
    )
    (ROOT / "frontend/lib/foundation/audio-modules.ts").write_text(source)
    print("Rendered and fingerprinted all 14 fixed chord voicings.")


if __name__ == "__main__":
    main()
